apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hayk-ss-1
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: hamatuni/pos
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myimagealias.update-strategy: latest

spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/hamatuni/pos-docker-images  # Can point to either a Helm chart repo or a git repo.
    targetRevision: main  # For Helm, this refers to the chart version.
    path: pos-helm  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

  # Destination cluster and namespace to deploy the application
  destination:
    server: 'https://cluster.eu-uncontrolled1.vineti.com:443'
    namespace: devops-upgrade-130
  syncPolicy:
    automated:
      prune: true # specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true 
      allowEmpty: true # allows deleting all application resources during automatic syncing ( false by default ).

